source ./brew.sh
source ./curl.sh
source ./wget.sh
source ./axel.sh
source ./jetbrains_mono.sh
source ./ohmyzsh.sh
source ./bat.sh
source ./z.sh
source ./fzf.sh
source ./z.sh
source ./vscode.sh
source ./sublime.sh
source ./tig.sh